# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  RESOURCEGROUP_LOGICAPPS: 'mcmaisasyncpat-rg'
  LOCATION_LOGICAPPS: 'westeurope'
  ORCHESTRATOR_LA_NAME: 'aisasync-orchestrator-la'
  SERVICEBUSQUEUE: 'customer-queue'
  PROCESSOR_LA_NAME: 'aisasync-processor-la'
  COSMOSCON: 'customer-con'
  API_NAME: 'Customer'
  API_OPERATION: 'create'
  API_PATH: 'customer'
  ORCHESTRATOR_LA_URLPATH: ''
  ORCHESTRATOR_LA_BASEURL: ''
  RESOURCEGROUP_SHARED: 'msaisd-rg'
  LOCATION_SHARED: 'westeurope'
  COSMOSACC: 'msaisd-acc'
  COSMOSDB: 'msaisd-db'
  APIM: 'msaisd'
  SERVICEBUSNS: 'msaisd-ns'
  LOGANALYTICS: 'msaisd-ws'
  APPINSIGHTS: 'msaisd-ai'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
